#!/usr/bin/env python3
"""
Phase-2.8C Position Runtime Report

职责：
- 生成持仓 Runtime 报告
- 只允许模拟盘/观察建议

Allowed actions:
- OBSERVE
- HOLD
- REDUCE_SIMULATION
- SKIP

Forbidden:
- BUY_REAL
- SELL_REAL
- AUTO_TRADE
"""

import json
from datetime import datetime
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
POSITION_FILES = [
    BASE_DIR / "paper_trading" / "paper_positions.json",
    BASE_DIR / "portfolio" / "paper_positions.json",
    BASE_DIR / "portfolio" / "positions.json",
]
STRUCTURE_FILE = BASE_DIR / "intraday_runtime" / "realtime_structure_runtime.json"
OUT_FILE = BASE_DIR / "runtime_reports" / "position_runtime_report.md"

ALLOWED_ACTIONS = {"OBSERVE", "HOLD", "REDUCE_SIMULATION", "SKIP"}


def _load(path, default=None):
    try:
        return json.loads(Path(path).read_text(encoding="utf-8"))
    except Exception:
        return default if default is not None else {}


def _load_positions():
    for path in POSITION_FILES:
        if path.exists():
            payload = _load(path, {})
            if isinstance(payload, list):
                return payload, str(path)
            for key in ("positions", "paper_positions", "holdings", "data"):
                if isinstance(payload.get(key), list):
                    return payload.get(key), str(path)
    return [], "not_found"


def _symbol(row):
    return row.get("股票代码") or row.get("symbol") or row.get("code") or ""


def _safe_action(position, structure_map):
    symbol = _symbol(position)
    structure = structure_map.get(symbol, {})
    if structure.get("runtime_data_stale_or_missing"):
        return "SKIP"
    if position.get("risk_flag") is True:
        return "REDUCE_SIMULATION"
    return "HOLD" if symbol else "OBSERVE"


def build_report():
    positions, source = _load_positions()
    structure_payload = _load(STRUCTURE_FILE, {})
    structure_map = {
        item.get("symbol"): item
        for item in structure_payload.get("structures", [])
        if item.get("symbol")
    }

    report = f"""# Position Runtime Report

Generated At: {datetime.now().isoformat()}

## System Mode

- PAPER_ONLY
- OBSERVE_ONLY

## Position Source

- Source: {source}
- Position Count: {len(positions)}

## Positions

"""

    if not positions:
        report += "- No paper positions found. Action: OBSERVE\n"
    else:
        for pos in positions:
            symbol = _symbol(pos)
            name = pos.get("股票名称") or pos.get("name") or ""
            structure = structure_map.get(symbol, {})
            action = _safe_action(pos, structure)
            if action not in ALLOWED_ACTIONS:
                action = "SKIP"

            report += f"### {symbol} {name}\n\n"
            report += f"- Structure: {structure.get('structure_type', 'UNKNOWN')}\n"
            report += f"- Support: {structure.get('support', 'UNKNOWN')}\n"
            report += f"- Pressure: {structure.get('pressure', 'UNKNOWN')}\n"
            report += f"- Runtime Stale: {structure.get('runtime_data_stale_or_missing', 'UNKNOWN')}\n"
            report += f"- Risk Flag: {pos.get('risk_flag', False)}\n"
            report += f"- Paper Action: {action}\n\n"

    report += "## Governance Constraint\n\nNo real trading instruction is generated by this report.\n"

    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(report, encoding="utf-8")
    print("Position Runtime Report generated")
    return report


if __name__ == "__main__":
    build_report()
